alias ls="ls --color=auto"
alias l="ls --color=auto -lA --time-style long-iso"
alias ll="ls --color=auto -la --time-style long-iso"
alias cd..="cd .."
alias ..="cd .."
alias ...="cd ../../"
alias ....="cd ../../../"
alias .....="cd ../../../../"
alias ff="find / -name"
alias f="find . -name"
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias fgrep="fgrep --color=auto"
alias ip="alias ip='ip -c'"
alias pacman="pacman --color auto"
alias pactree="pactree --color"
alias vdir="vdir --color=auto"
alias watch="watch --color"
alias man="color function"
alias yay="sudo -u norman yay"
alias browser="midori &"
alias panic="kali-undercover"
alias ku="kali-undercover"
alias qwer="kali-undercover"
